GET http://localhost:5273/categories

###
GET http://localhost:5273/categories/25

###
POST http://localhost:5273/categories
Content-Type: application/json

{
    "name": "Work",
    "description": "Tasks related to work",
    "userId": 1

}

###
PUT http://localhost:5273/categories/4
Content-Type: application/json

{
    "name": "asded",
    "description": "najjar relateghfghfhg to personal life"
   
   
}

### Delete a category by ID
DELETE http://localhost:5273/categories/55
