### Task Management

# Create a new task
POST http://localhost:5273/tasks
Content-Type: application/json

{
  "title": "مهمة جديدة",
    "description": "وصف المهمة",
    "dueDate": "2024-12-31",
    "priority": 2,
    "userId": 1,
    "categoryId": 1,
    "status": "Pending"
}

# Get a task by ID
GET http://localhost:5273/tasks/1


# Update an existing task
PUT http://localhost:5000/api/tasks/2
Content-Type: application/json

{
    "title": "Updated Task Title",
    "description": "Updated description",
    "dueDate": "2024-12-15",
    "status": "Completed",
    "categoryId": 2,
    "priority": "Medium"
}

# Delete a task
DELETE http://localhost:5000/api/tasks/2


