# Get all tasks
GET http://localhost:5273/tasks

# Get a specific task by ID
GET http://localhost:5273/tasks/10

# Create a new task
POST http://localhost:5273/tasks
Content-Type: application/json

{
     "title": "Complete the project",
     "description": "Finalize the API endpoints for the task management system.",
     "releaseDate": "2025-11-05",
     "isCompleted": false,
     "priority": 1,
     "userId": 1,
     "stutus" "ok"
     "categoryId": 1
}

# Update an existing task
PUT http://localhost:5273/tasks/3
Content-Type: application/json

{
    "title": "Update the task",
    "description": "Revise the task details for accuracy.",
    "isCompleted": true,
    "priority": 2,
    "userId": 1,
    "categoryId": 2
}

# Delete a task by ID
DELETE http://localhost:5273/tasks/4
