POST http://localhost:5273/users/register
Content-Type: application/json

{
   "UserName": "mohammed2",
  "Password": "password123"
}

###
POST http://localhost:5273/users/login 
Content-Type: application/json

{
  "UserName": "mohammed najjar",
  "Password": "password123"
}

###
GET http://localhost:5273/users/5



